# Generated by Django 3.2 on 2021-04-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_id'),
        ('event', '0003_alter_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
