# Generated by Django 3.2 on 2021-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20210415_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event_date',
            field=models.DateField(default=None),
        ),
    ]
