# Generated by Django 3.2 on 2021-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_eventtime_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
